'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ControlPropertiesChangeOnCallback


    Partial Public Class _Default

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' cpCallbackPanel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected cpCallbackPanel As Global.DevExpress.Web.ASPxCallbackPanel

        ''' <summary>
        ''' hfPageState control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected hfPageState As Global.DevExpress.Web.ASPxHiddenField

        ''' <summary>
        ''' btnButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnButton As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnChangePropertiesOnCallback control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnChangePropertiesOnCallback As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnChangePropertiesOnClient control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnChangePropertiesOnClient As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnSendEmptyCallback control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnSendEmptyCallback As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnDoPostback control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnDoPostback As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
